# Server Configuration
server.port=80
server.servlet.context-path=/user-resource-service
spring.application.name=user-resource-service

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}/identity
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.hikari.maximum-pool-size=${POSTGRES_POOL_SIZE}

# HikariCP Configuration
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000

# JPA/Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.security.enabled=true
jwt.security.jwks-url=https://${API_GW}/gw/oauth2/jwks

# Redis Cache Configuration
thales.cache.type=REDIS
thales.cache.enabled=true
thales.redis.host=${REDIS_HOST:localhost}
thales.redis.port=${REDIS_PORT:6379}
thales.redis.password=${REDIS_PASSWORD}
thales.cache.ttl.tempUsers=1800s

# User Verification Configuration
user.verification.link-template=https://${DOMAIN}/confirmation/{code}

# OpenAPI/Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.filter=true
springdoc.server.url=http://${API_INTERNAL}/user-resource-service
springdoc.api-docs.version=OPENAPI_3_0
springdoc.default-produces-media-type=application/json
springdoc.default-consumes-media-type=application/json
springdoc.swagger-ui.oauth.client-id=user-resource-service
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.persist-authorization=true

services.notification-service.url=http://${NOTIFICATION_SERVICE_NAME}/notification-service

#Domain URL
thales.url.base=${DOMAIN}
portal.user.allowed-domain=${PROD_DOMAIN}
