package com.thales.user_resource_service.util;

import com.thales.user_resource_service.dto.PortalUserCreateRequest;
import com.thales.user_resource_service.dto.PortalUserResponse;
import com.thales.user_resource_service.dto.UserBaseResponse;
import com.thales.user_resource_service.dto.UserCreateOrGetRequest;
import com.thales.user_resource_service.dto.UserCreateRequest;
import com.thales.user_resource_service.dto.UserResponse;
import com.thales.user_resource_service.model.PortalUser;
import com.thales.user_resource_service.model.User;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Test data factory - creates mock objects for testing
 */
public class TestDataFactory {

    public static User createUser() {
        return User.builder()
                .id(1L)
                .username("testuser")
                .email("test@example.com")
                .password("encoded_password")
                .authProvider("LOCAL")
                .birthDate(LocalDate.of(1990, 1, 1))
                .createdAt(LocalDateTime.now())
                .updatedAt(LocalDateTime.now())
                .build();
    }
    
    public static User createUser(Long id, String username, String email) {
        return User.builder()
                .id(id)
                .username(username)
                .email(email)
                .password("encoded_password")
                .authProvider("LOCAL")
                .birthDate(LocalDate.of(1990, 1, 1))
                .createdAt(LocalDateTime.now())
                .updatedAt(LocalDateTime.now())
                .build();
    }

    public static User createUser(String username, String email) {
        return User.builder()
                .id(null)  // ID will be generated by the database
                .username(username)
                .email(email)
                .password("encoded_password")
                .authProvider("LOCAL")
                .birthDate(LocalDate.of(1990, 1, 1))
                .createdAt(LocalDateTime.now())
                .updatedAt(LocalDateTime.now())
                .build();
    }

    public static UserCreateRequest createUserCreateRequest() {
        return UserCreateRequest.builder()
                .username("testuser")
                .email("test@example.com")
                .password("password123")
                .birthDate(LocalDate.of(1990, 1, 1))
                .build();
    }
    
    public static UserCreateRequest createUserCreateRequest(String username, String email) {
        return UserCreateRequest.builder()
                .username(username)
                .email(email)
                .password("password123")
                .birthDate(LocalDate.of(1990, 1, 1))
                .build();
    }

    public static UserCreateRequest createUserRequest(String username, String email, String password) {
        return UserCreateRequest.builder()
                .username(username)
                .email(email)
                .password(password)
                .birthDate(LocalDate.of(1990, 1, 1))
                .build();
    }

    public static UserCreateOrGetRequest createUserCreateOrGetRequest() {
        return UserCreateOrGetRequest.builder()
                .username("testuser")
                .email("test@example.com")
                .authProvider("GOOGLE")
                .externalId("google_123456")
                .birthDate(LocalDate.of(1990, 1, 1))
                .build();
    }
    
    public static UserCreateOrGetRequest createUserCreateOrGetRequest(String username, String email, String provider) {
        return UserCreateOrGetRequest.builder()
                .username(username)
                .email(email)
                .authProvider(provider)
                .externalId(provider + "_123456")
                .birthDate(LocalDate.of(1990, 1, 1))
                .build();
    }

    public static UserResponse createUserResponse() {
        return UserResponse.builder()
                .id(1L)
                .username("testuser")
                .email("test@example.com")
                .authProvider("LOCAL")
                .birthDate(LocalDate.of(1990, 1, 1))
                .createdAt(LocalDateTime.now())
                .updatedAt(LocalDateTime.now())
                .build();
    }
    
    public static UserResponse createUserResponse(Long id, String username, String email, String provider) {
        return UserResponse.builder()
                .id(id)
                .username(username)
                .email(email)
                .authProvider(provider)
                .externalId(provider.equals("LOCAL") ? null : provider + "_123456")
                .birthDate(LocalDate.of(1990, 1, 1))
                .createdAt(LocalDateTime.now())
                .updatedAt(LocalDateTime.now())
                .build();
    }

    public static UserBaseResponse createUserBaseResponse() {
        return new UserBaseResponse(1L, "testuser");
    }
    
    public static UserBaseResponse createUserBaseResponse(Long id, String username) {
        return new UserBaseResponse(id, username);
    }
    
    // PortalUser test data methods
    
    public static PortalUser createPortalUser() {
        return PortalUser.builder()
                .id(1L)
                .username("portaltestuser")
                .email("portaltest@thales.com")
                .password("encoded_password")
                .fullName("Test Portal User")
                .department("IT")
                .role("DEVELOPER")
                .isActive(true)
                .createdAt(LocalDateTime.now())
                .updatedAt(LocalDateTime.now())
                .build();
    }
    
    public static PortalUser createPortalUser(Long id, String username, String email) {
        return PortalUser.builder()
                .id(id)
                .username(username)
                .email(email)
                .password("encoded_password")
                .fullName("Test Portal User")
                .department("IT")
                .role("DEVELOPER")
                .isActive(true)
                .createdAt(LocalDateTime.now())
                .updatedAt(LocalDateTime.now())
                .build();
    }
    
    public static PortalUserCreateRequest createPortalUserCreateRequest() {
        return PortalUserCreateRequest.builder()
                .username("portaltestuser")
                .email("portaltest@thales.com")
                .password("password123")
                .fullName("Test Portal User")
                .department("IT")
                .role("DEVELOPER")
                .build();
    }
    
    public static PortalUserCreateRequest createPortalUserCreateRequest(String username, String email) {
        return PortalUserCreateRequest.builder()
                .username(username)
                .email(email)
                .password("password123")
                .fullName("Test Portal User")
                .department("IT")
                .role("DEVELOPER")
                .build();
    }
    
    public static PortalUserResponse createPortalUserResponse() {
        return PortalUserResponse.builder()
                .id(1L)
                .username("portaltestuser")
                .email("portaltest@thales.com")
                .fullName("Test Portal User")
                .department("IT")
                .role("DEVELOPER")
                .active(true)
                .createdAt(LocalDateTime.now())
                .updatedAt(LocalDateTime.now())
                .build();
    }
    
    public static PortalUserResponse createPortalUserResponse(Long id, String username, String email) {
        return PortalUserResponse.builder()
                .id(id)
                .username(username)
                .email(email)
                .fullName("Test Portal User")
                .department("IT")
                .role("DEVELOPER")
                .active(true)
                .createdAt(LocalDateTime.now())
                .updatedAt(LocalDateTime.now())
                .build();
    }
} 